apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/sjondegast/kind-argocd-self-managed.git
      revision: HEAD
      directories:
      - path: cluster-infra-config/add-ons/*
      - exclude: true
        path: cluster-infra-config/add-ons/cert-manager
      - exclude: true
        path: cluster-infra-config/add-ons/keycloak-operator
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/sjondegast/kind-argocd-self-managed.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true