apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-demo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-guestbook-demo
    name: in-cluster
  project: sample-project
  source:
    path: kustomized_helm/overlays/dev
    repoURL: https://github.com/d0-labs/argocd-app-of-apps-child-guestbook
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    # plugin:
    #   name: kustomized-helm
