apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team2-guestbook
  namespace: argocd
spec:
  project: team2
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true